# docker-compose-dev.yml
version: "3.9"

services:
  # TODO: add vault service
  xurya-calculator:
    image: "asia.gcr.io/xuryaeligibility/xurya-calculator:dev"
    # TODO: integrate with the vault to start the server
    entrypoint: []
    # start the server
    command: "/bin/sh -c 'bun run src/index.ts'"
    # expose the right ports
    ports: ["8000:8000"]
