# docker-compose-dev.yml
services:
  elysia:
    image: "elysia:latest"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./temp:/temp
    # expose ports
    ports: ["8000:8000"]

    # resources limitation
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
