# docker-compose-local.yml
version: "3.9"

services:
  xurya-calculator:
    image: "asia.gcr.io/xuryaeligibility/xurya-calculator:local"
    # override default entrypoint allows us to do `bun install` before serving
    entrypoint: []
    # execute bun install before we start the dev server in watch mode
    command: "/bin/sh -c 'bun install && bun run --watch src/index.ts'"
    # expose the right ports
    ports: ["8000:8000"]
    # setup a host mounted volume to sync changes to the container
    volumes: ["./:/home/bun/app"]
